# -*- coding: utf-8 -*-
"""rectangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aBnxodBpeMagNTONw9eTDxmAvxwdu9q2
"""

class Rectangle: 
    def __init__(self, length , width):
        self.length = length
        self.width = width

#a.Primeter() method
    def Perimeter(self):
        return 2*(self.length + self.width)


    def Area(self):
        return self.length*self.width

#b.Display() method

    def display(self):
        print("Length of Rectangle: ", self.length)
        print("Width of Rectangle: ", self.width)
        print("Perimeter of Rectangle: ", self.Perimeter())
        print("Area of Rectangle: ", self.Area())

#c.Parallelepiped child class inheriting from the Rectangle

class Parallelepipede(Rectangle):
    def __init__(self, length, width , height):
        Rectangle.__init__(self, length, width)
        self.height = height
  

    def volume(self):
        return print('Volume of Parallelepiped:' ,self.length*self.width*self.height)
        
Rectangle(5,4)
parallelepipede = Parallelepipede(5,4,2)
Rectangle(5,4).display()
parallelepipede.volume()